import math
a=float(input("Enter the number:"))
x=int(input("Enter the number:"))
print("absolute value=",abs(x))
print("ceil=",math.ceil(a))
print("exponent=",math.exp(x))
n1=int(input("Enter 1st value:"))
n2=int(input("Enter 2nd value:"))
x=max(n1,n2)
print("max value=",x)
x=min(n1,n2)
print("min value=",x)
p=pow(n1,n2)
print("power=",p)
q=int(input("enter the no:"))
print("sqrt=",math.sqrt(q))
